bases:
- ../base
resources:
- config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: webhook-configmap
  files:
  - webhookconfig.yaml
  behavior: merge
- name: nginx-configmap
  files:
  - nginx.conf
  behavior: merge
