resources:
- config.yaml
- deployment.yaml
- mutatingwebhook.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: webhook-server-cert
  files:
  - ca.bundle=ca.bundle
- name: sidecar-injector-webhook-configmap
  files:
  - sidecarconfig.yaml
  behavior: merge
- name: nginx-configmap
  files:
  - nginx.conf
  behavior: merge
vars:
  - name: CABUNDLE
    objref:
      kind: ConfigMap
      version: v1
      name: webhook-server-cert
    fieldref:
      fieldpath: data[ca.bundle]
