apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutating-webhook
  labels:
    app: pod-mutating-webhook
webhooks:
  - name: pod-mutating-webhook.spring.io
    clientConfig:
      service:
        name: pod-mutating-webhook
        namespace: default
        path: "/mutate"
      caBundle: $(CABUNDLE)
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
