annotations:
  prometheus.io/path: /actuator/prometheus
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
containers:
  - name: demo
    livenessProbe:
      httpGet:
        path: /actuator/info
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 3
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      httpGet:
        path: /actuator/health
        port: 8080